In [2]:
import pandas as pd
df = pd.read_csv("../reports/students_cleaned.csv")

In [6]:
df.isnull()  #Finding missing values
df.isnull().sum() # Count missing values
df[df.isnull().any(axis=1)]

     Name  Math  Physics  Chemistry
6  Meryem    78      NaN         80

In [2]:
#Fill missing value with average
df['Physics'] = df['Physics'].fillna(df['Physics'].mean())
df.to_csv("../reports/students_missing_cleaned.csv",index = False)

'\ndf[\'Physics\'] = df[\'Physics\'].fillna(df[\'Physics\'].mean())\ndf.to_csv("../reports/students_missing_cleaned.csv",index = False)\n'

In [10]:
#------------Finding duplicate Rows
df.duplicated()
print(df.duplicated().sum())
print(df[df.duplicated()])
df = df.drop_duplicates()
print(df.duplicated().sum())
df.to_csv("../reports/students_duplicates_cleaned.csv",index = False)

0
Empty DataFrame
Columns: [Name, Math, Physics, Chemistry]
Index: []
0

In [3]:
#-------Fix Invalid Scores
df.loc[df['Math'] > 100, 'Math'] =  100
#--------Recalculate average
df['Average'] = (df['Math'] + df['Physics'] + df['Chemistry'])/3
df['Average'] = df['Average'].round(2)   
df.to_csv("../reports/students_invalide_scores_cleaned.csv", index = False)   #Save

     Name  Math  Physics  Chemistry  Average
0   Ahmed    80     75.0         90    81.67
1    Sara    95     88.0         91    91.33
2    John    70     60.0         75    68.33
3  Fatima    88     92.0         85    88.33
4     Ali    65     70.0         60    65.00
5   Yusuf    90     89.0         93    90.67
6  Meryem    78      NaN         80      NaN
7    Adam    85     79.0         88    84.00
8    Sara    95     88.0         91    91.33
9   Karim   100     70.0         85    85.00

In [3]:
#---Cleaning on the same data

#Fill missing value with the average
df['Physics'] = df['Physics'].fillna(df['Physics'].mean())

#Drop duplicates
df = df.drop_duplicates()

#Fix invalid Scores
df.loc[df['Math'] > 100, 'Math'] = 100

#Recalculate Average because the data changed
df['Average'] =(df['Math'] + df['Physics'] + df['Chemistry'] )/3
df['Average'] = df['Average'].round(2)
df.to_csv("../reports/students_cleaned.csv",index=False)

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       9 non-null      str
 1   Math       9 non-null      int64
 2   Physics    9 non-null      float64
 3   Chemistry  9 non-null      int64
 4   Average    9 non-null      float64
dtypes: float64(2), int64(2), str(1)
memory usage: 492.0 bytes

             Math    Physics  Chemistry    Average
count    9.000000   9.000000    9.00000   9.000000
mean    83.444444  78.000000   83.00000  81.481111
std     11.381027  10.488088   10.29563   9.339709
min     65.000000  60.000000   60.00000  65.000000
25%     78.000000  70.000000   80.00000  79.000000
50%     85.000000  79.000000   85.00000  84.000000
75%     90.000000  88.000000   90.00000  88.330000
max    100.000000  92.000000   93.00000  91.330000