In [1]:
import pandas as pd
df = pd.read_csv("../data/student_messy.csv")

In [6]:
df.isnull()  #Finding missing values
df.isnull().sum() # Count missing values
df[df.isnull().any(axis=1)]

     Name  Math  Physics  Chemistry
6  Meryem    78      NaN         80

In [2]:
#Fill missing value with average
df['Physics'] = df['Physics'].fillna(df['Physics'].mean())
df.to_csv("../reports/students_missing_cleaned.csv",index = False)

'\ndf[\'Physics\'] = df[\'Physics\'].fillna(df[\'Physics\'].mean())\ndf.to_csv("../reports/students_missing_cleaned.csv",index = False)\n'

In [10]:
#------------Finding duplicate Rows
df.duplicated()
print(df.duplicated().sum())
print(df[df.duplicated()])
df = df.drop_duplicates()
print(df.duplicated().sum())
df.to_csv("../reports/students_duplicates_cleaned.csv",index = False)

0
Empty DataFrame
Columns: [Name, Math, Physics, Chemistry]
Index: []
0

In [3]:
#-------Fix Invalid Scores
df.loc[df['Math'] > 100, 'Math'] =  100
#--------Recalculate average
df['Average'] = (df['Math'] + df['Physics'] + df['Chemistry'])/3
df['Average'] = df['Average'].round(2)   
df.to_csv("../reports/students_invalide_scores_cleaned.csv", index = False)   #Save

     Name  Math  Physics  Chemistry  Average
0   Ahmed    80     75.0         90    81.67
1    Sara    95     88.0         91    91.33
2    John    70     60.0         75    68.33
3  Fatima    88     92.0         85    88.33
4     Ali    65     70.0         60    65.00
5   Yusuf    90     89.0         93    90.67
6  Meryem    78      NaN         80      NaN
7    Adam    85     79.0         88    84.00
8    Sara    95     88.0         91    91.33
9   Karim   100     70.0         85    85.00